"""IUPAC name and parent-structure locants, without guessing.

1. The name comes from PubChem, looked up by the molecule's full InChIKey (an exact structure match,
   stereochemistry included). PubChem's names are generated by OpenEye Lexichem.
2. OPSIN (an open-source name-to-structure parser) rebuilds the structure from each candidate name and
   reports a locant for every atom. A name is used only if its structure equals ours (connectivity and
   charges); if several different names fit, none is used.
3. OPSIN numbers every substituent in its own scheme (ibuprofen's phenyl is 1-6 as well as the
   propanoic-acid chain 1-3). The atoms are split into numbering schemes, and the parent scheme is the
   one whose attachment points are exactly the top-level locants of the name. Locants are reported only
   for the parent, and only for atoms that receive the same locant under every mapping of OPSIN's
   structure onto ours (symmetry).

Whenever a step is not certain, the result says why and gives no locants.
"""
import asyncio
import os
import re
import xml.etree.ElementTree as ET
from functools import lru_cache
from pathlib import Path

import httpx
from rdkit import Chem

OPSIN_JAR = Path(os.getenv("MOLTALK_OPSIN_JAR",
                           Path(__file__).resolve().parent.parent / "vendor" / "opsin-cli-2.9.0-jar-with-dependencies.jar"))
OFFLINE = os.getenv("MOLTALK_OFFLINE") == "1"
CML = "{http://www.xml-cml.org/schema}"
LOCANT = re.compile(r"^(\d+)([a-z]?)$")
BOND = {"1": Chem.BondType.SINGLE, "2": Chem.BondType.DOUBLE, "3": Chem.BondType.TRIPLE, "S": Chem.BondType.SINGLE,
        "D": Chem.BondType.DOUBLE, "T": Chem.BondType.TRIPLE, "A": Chem.BondType.AROMATIC}
_names: dict[str, list] = {}
_pubchem_lock = asyncio.Lock()
_pubchem_last = 0.0
PUBCHEM_MIN_INTERVAL_S = 0.25  # at most 4 requests per second (PubChem asks for no more than 5)


async def pubchem_slot():
    """Wait for our turn so the whole server stays under PubChem's request-rate limit."""
    global _pubchem_last
    async with _pubchem_lock:
        wait = _pubchem_last + PUBCHEM_MIN_INTERVAL_S - asyncio.get_running_loop().time()
        if wait > 0:
            await asyncio.sleep(wait)
        _pubchem_last = asyncio.get_running_loop().time()
_cml: dict[str, str | None] = {}


async def pubchem_names(inchikey: str) -> list[dict] | None:
    """[{cid, name}] for every PubChem record with exactly this InChIKey; [] if none; None if unreachable."""
    if inchikey in _names:
        return _names[inchikey]
    url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/inchikey/{inchikey}/property/IUPACName/JSON"
    try:
        await pubchem_slot()
        async with httpx.AsyncClient(timeout=8, follow_redirects=False) as client:
            response = await client.get(url)
    except httpx.HTTPError:
        return None
    if response.status_code == 404:
        records = []
    elif response.status_code != 200:
        return None
    else:
        records = [{"cid": r["CID"], "name": r["IUPACName"]} for r in response.json()["PropertyTable"]["Properties"]
                   if r.get("IUPACName")]
    _names[inchikey] = records
    return records


async def opsin_cml(name: str) -> str | None:
    """OPSIN's CML for a name (with per-atom locants), or None if OPSIN cannot read it."""
    if name in _cml:
        return _cml[name]
    if not OPSIN_JAR.exists():
        return None
    try:
        # Small heap and serial GC: OPSIN needs little memory, and a cloud container has little to spare.
        proc = await asyncio.create_subprocess_exec("java", "-Xmx256m", "-XX:+UseSerialGC", "-XX:TieredStopAtLevel=1",
                                                    "-jar", str(OPSIN_JAR), "-ocml", stdin=asyncio.subprocess.PIPE,
                                                    stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL)
        out, _ = await asyncio.wait_for(proc.communicate(name.encode() + b"\n"), timeout=20)
    except (OSError, asyncio.TimeoutError):
        return None
    text = out.decode(errors="replace")
    _cml[name] = text if "<atom" in text else None
    return _cml[name]


def _cml_molecule(cml: str):
    """RDKit molecule (heavy atoms, in CML order) and each atom's OPSIN labels."""
    root = ET.fromstring(cml)
    rw, ids, labels = Chem.RWMol(), {}, {}
    for a in root.iter(CML + "atom"):
        atom = Chem.Atom(a.get("elementType"))
        atom.SetFormalCharge(int(a.get("formalCharge", 0)))
        atom.SetNoImplicit(True)
        idx = rw.AddAtom(atom)
        ids[a.get("id")] = idx
        labels[idx] = [l.get("value") for l in a.findall(CML + "label")]
    for b in root.iter(CML + "bond"):
        x, y = b.get("atomRefs2").split()
        rw.AddBond(ids[x], ids[y], BOND[b.get("order")])
    for a in root.iter(CML + "atom"):  # hydrogens given as a count rather than as atoms
        if a.get("hydrogenCount") is not None:
            atom = rw.GetAtomWithIdx(ids[a.get("id")])
            explicit = sum(1 for n in atom.GetNeighbors() if n.GetAtomicNum() == 1)
            atom.SetNumExplicitHs(max(0, int(a.get("hydrogenCount")) - explicit))
    mol = rw.GetMol()
    Chem.SanitizeMol(mol)
    keep = [a.GetIdx() for a in mol.GetAtoms() if a.GetAtomicNum() > 1]
    return Chem.RemoveHs(mol), [labels[i] for i in keep]


def _same(a, b) -> bool:
    return Chem.MolToSmiles(a, isomericSmiles=False) == Chem.MolToSmiles(b, isomericSmiles=False)


def _locant(labels):
    """The atom's plain locant ('3', '6a'), if its first label is one; primed or non-numeric labels give None."""
    return labels[0] if labels and LOCANT.match(labels[0]) else None


def _key(locant):
    m = LOCANT.match(locant)
    return int(m.group(1)), m.group(2)


def _in_sequence(p, q, ring_max):
    """Could two bonded atoms with locants p and q belong to the same numbering scheme?"""
    (a, x), (b, y) = _key(p), _key(q)
    if not x and not y:
        return abs(a - b) == 1 or {a, b} == {1, ring_max}
    return a == b or abs(a - b) == 1 or (x and y)  # fused positions: 3-3a, 3a-4, 10b-10c, 6a-7


def _schemes(mol, locants, labels):
    """Split atoms into numbering schemes; returns a list of atom sets, or None if the split is ambiguous."""
    numbered = [i for i, l in enumerate(locants) if l]
    ring_max = max((_key(locants[i])[0] for i in numbered), default=0)
    lone = {i for i, l in enumerate(labels) if "C" in l[1:]}  # OPSIN marks one-carbon substituents (methyl) with 'C'
    edges = set()
    for b in mol.GetBonds():
        x, y = b.GetBeginAtomIdx(), b.GetEndAtomIdx()
        if not (locants[x] and locants[y]) or x in lone or y in lone:
            continue
        # Fused and bridged rings join non-consecutive locants (steroid C5-C10); a ring bond is always internal.
        if b.IsInRing() or _in_sequence(locants[x], locants[y], ring_max):
            edges.add((x, y))

    def components(edge_set):
        parent = {i: i for i in numbered}

        def find(i):
            while parent[i] != i:
                parent[i] = parent[parent[i]]
                i = parent[i]
            return i
        for x, y in edge_set:
            parent[find(x)] = find(y)
        groups = {}
        for i in numbered:
            groups.setdefault(find(i), set()).add(i)
        return list(groups.values())

    def duplicated(group):
        seen = [locants[i] for i in group]
        return len(seen) != len(set(seen))

    # A substituent bonded to a neighbouring locant (phenyl C1 on propanoic C2) merges two schemes; cut exactly
    # one bond so that both halves have unique locants. If no single cut works, or several do, give up.
    for _ in range(len(edges)):
        bad = next((g for g in components(edges) if duplicated(g)), None)
        if bad is None:
            return components(edges)
        cuts = []
        for edge in [e for e in edges if e[0] in bad]:
            rest = edges - {edge}
            parts = [g for g in components(rest) if g & bad]
            if len(parts) == 2 and not any(duplicated(g) for g in parts):
                cuts.append(edge)
        if len(cuts) != 1:
            return None
        edges = edges - {cuts[0]}
    return None


def _top_level_locants(name: str) -> set[str]:
    """Numeric locants written outside brackets: '3-methyl', '2-[...]', '(6aR,9R)', 'butan-2-ol', '-2,6-dione'."""
    depth, flat = 0, []
    for ch in name:
        if ch in "[(":
            depth += 1
            if depth == 1 and ch == "(":
                flat.append(" ")
            continue
        if ch in "])":
            depth -= 1
            continue
        flat.append(ch if depth == 0 else " ")
    text = "".join(flat)
    found = set()
    for group in re.findall(r"(?<![\w'])((?:\d+[a-z]?[RSEZH]?,)*\d+[a-z]?[RSEZH]?)(?=[-,\s]|$)", text):
        for part in group.split(","):
            m = re.match(r"^(\d+[a-z]?)", part)
            if m:
                found.add(m.group(1))
    # stereodescriptors written in brackets at the start, e.g. (6aR,9R)-...
    for group in re.findall(r"^\(([^)]*)\)", name):
        for part in group.split(","):
            m = re.match(r"^(\d+[a-z]?)[RSEZ]$", part.strip())
            if m:
                found.add(m.group(1))
    return found


def _parent_locants(ref, labels, name):
    """{OPSIN atom index: locant} for the parent scheme, or (None, reason).

    The parent must contain every top-level locant of the name, and its bonds to other numbered carbon schemes
    must leave from top-level positions ('3-methyl' -> parent C3). If several schemes qualify, the one whose
    top-level positions actually carry something outside it wins; a remaining tie means no locants."""
    locants = [_locant(l) for l in labels]
    schemes = _schemes(ref, locants, labels)
    if not schemes:
        return None, "the numbering schemes in the name could not be separated unambiguously"
    top = _top_level_locants(name)
    scored = []
    for group in schemes:
        mine = {locants[i] for i in group}
        attach = {locants[i] for i in group for nb in ref.GetAtomWithIdx(i).GetNeighbors()
                  if nb.GetIdx() not in group and nb.GetAtomicNum() == 6 and locants[nb.GetIdx()]}
        if top <= mine and attach <= top:
            bearing = sum(1 for i in group if locants[i] in top
                          and any(nb.GetIdx() not in group for nb in ref.GetAtomWithIdx(i).GetNeighbors()))
            scored.append((bearing, group))
    if not scored:
        return None, "the parent chain or ring of the name could not be identified"
    scored.sort(key=lambda t: -t[0])
    if len(scored) > 1 and scored[0][0] == scored[1][0]:
        return None, "the parent chain or ring of the name could not be identified unambiguously"
    return {i: locants[i] for i in scored[0][1]}, None


def _stereo_descriptors(name):
    """{locant: 'R'/'S'} from the name's leading descriptors, e.g. '(1R,2S,5R)-' or 'cis-(1R,3S)-'."""
    m = re.match(r"^(?:(?:cis|trans|rel)-)?\(([^)]*)\)-", name)
    found = {}
    for part in (m.group(1).split(",") if m else []):
        d = re.match(r"^(\d+[a-z]?)([RS])$", part.strip())
        if d:
            found[d.group(1)] = d.group(2)
    return found


def _map_locants(mol, ref, parent, descriptors):
    """Locants on our atoms. Symmetry-equivalent numberings (cyclohexanone C2 or C6) are equally valid, so the
    first is used, but only a numbering under which every R/S descriptor in the name matches our own CIP label;
    if none does, nothing is returned."""
    cip = {a.GetIdx(): a.GetProp("_CIPCode") for a in mol.GetAtoms() if a.HasProp("_CIPCode")}
    for match in mol.GetSubstructMatches(ref, uniquify=False, useChirality=False, maxMatches=5000):
        numbering = {our_i: parent[ref_i] for ref_i, our_i in enumerate(match) if ref_i in parent}
        by_locant = {loc: i for i, loc in numbering.items()}
        if all(cip.get(by_locant.get(loc)) == rs for loc, rs in descriptors.items()):
            return numbering
    return {}


def locants_from_cml(smiles: str, name: str, cml: str):
    """Pure RDKit work (runs in the worker pool): ({atom index: locant}, None) or (None, reason)."""
    from rdkit.Chem import rdCIPLabeler
    mol = Chem.MolFromSmiles(smiles)
    rdCIPLabeler.AssignCIPLabels(mol)
    ref, labels = _cml_molecule(cml)
    if not _same(ref, mol):
        return None, "the name's structure does not match"
    parent, reason = _parent_locants(ref, labels, name)
    if parent is None:
        return None, reason
    found = _map_locants(mol, ref, parent, _stereo_descriptors(name))
    if not found:
        return None, "no numbering of the parent matches the name's stereodescriptors"
    return {str(i): l for i, l in sorted(found.items())}, None


def matches_structure(smiles: str, cml: str) -> bool:
    return _same(_cml_molecule(cml)[0], Chem.MolFromSmiles(smiles))


def _variants(name: str):
    yield name
    # 'cis-(1R,3S)-…': the R/S descriptors already fix the geometry; OPSIN rejects the redundant prefix.
    stripped = re.sub(r"^(?:cis|trans)-(?=\()", "", name)
    if stripped != name:
        yield stripped


async def name_and_locants(smiles: str, run) -> dict:
    """{iupac_name, name_source, name_status, locants, locant_status}. run(fn, *args) executes RDKit work."""
    mol = Chem.MolFromSmiles(smiles)
    result = {"iupac_name": None, "name_source": None, "locants": {}, "locant_status": None}
    if OFFLINE:
        result["name_status"] = "name lookup is turned off (MOLTALK_OFFLINE=1)"
        return result
    records = await pubchem_names(Chem.MolToInchiKey(mol))
    if records is None:
        result["name_status"] = "PubChem could not be reached"
        return result
    if not records:
        result["name_status"] = "this exact structure is not in PubChem, so no IUPAC name is given (not guessed)"
        return result
    # Keep only names whose own structure is exactly ours (drops zwitterion and salt duplicates).
    readable = []
    for record in records:
        for variant in _variants(record["name"]):
            cml = await opsin_cml(variant)
            if cml and await run(matches_structure, smiles, cml):
                readable.append((record, variant, cml))
                break
    distinct = {r["name"] for r, _, _ in readable}
    if len(distinct) > 1:
        result["name_status"] = "PubChem lists several different names for this structure; none is chosen"
        return result
    if not readable:
        # The InChIKey match is exact, so PubChem's name is right, but its numbering cannot be read.
        if len({r["name"] for r in records}) == 1:
            result.update(iupac_name=records[0]["name"], name_source=f"PubChem CID {records[0]['cid']}",
                          name_status="ok", locant_status="the name could not be parsed, so atoms are not numbered")
        else:
            result["name_status"] = "PubChem lists several different names for this structure; none is chosen"
        return result
    record, variant, cml = readable[0]
    result.update(iupac_name=record["name"], name_source=f"PubChem CID {record['cid']}", name_status="ok")
    locants, reason = await run(locants_from_cml, smiles, variant, cml)
    if locants:
        result["locants"] = locants
        result["locant_status"] = "ok"
    else:
        result["locant_status"] = f"atoms are not numbered: {reason}"
    return result
